dist: xenial
language: python
python: "3.7"

stages:
  - name: static analysis
  - name: test
  - name: deploy to pypi
    if: type = push AND tag =~ ^\d+\.\d+\.\d+

jobs:
  include:
    - stage: static analysis
      install: pip install flake8
      script: flake8 anyio tests

    - stage: static analysis
      install: pip install mypy
      script: mypy anyio

    - &test
      stage: test
      python: "3.5.3"
      after_success:
        - pip install coveralls
        - coveralls

    - <<: *test
      python: "3.6"

    - <<: *test
      python: "3.7"

    - <<: *test
      python: pypy3.5-6.0
      env: PYTEST_ADDOPTS="--no-cov"
      after_success: skip

    - <<: *test
      os: osx
      language: sh
      python: "3.7"
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
      env: HOMEBREW_NO_INSTALL_CLEANUP=1

    - <<: *test
      os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip

    - stage: deploy to pypi
      install: true
      script: skip
      deploy:
        provider: pypi
        user: agronholm
        password:
          secure: zHprICvuiBq7hVNv7n/a9uyXaNPmYPu+r5YvwBdjt6QlikrCW1ArOSH6/fvySwFRsVXe0KJbqNCCmmoAMWSxo1LtBYU/fsCn5vXfq5D6XJIDBzf4sl2AS0SpqLpsLtnj/3g62NK9lXQfoExrcUuwAPLV84htsKACaNtxCLA8KB+sLtkiePt42j31BuClfzMg9eDaDlyHBrLBFiBYOWrOatprIaEL0FF3Dt6LzeANRvnjkzy3Gvn8/HgUSF1fCLcsqpSm5uopf4zYCBeZpKdUFYd4rCmfz973uJl2z6Jq1Lmyzb6G2ToUnQal59jNrSrMlwo1dKUS1To1Uw6PckGFPnYyoCz3/598TVo6cP/yJl18rN4tN86KhOw+agSOcpQcBVWPcNTvEnxrCnPQGL1SfoWyCWX31cHnZDnTzAC/FeqWWAmrlDv3jEzdyFyGhWZov8OE3unsOO3q8pF+qJd87GYxulJpn4jB2my9VGWx0GFttR09GF7jLUhecnKviwaWo5fFTZc7strUK+Kun9rchxoHhefn8+d96uMm6uVDa+U6h2gNGPY4FEFyMoMn8qYytLHTcIsurWNlEh+I25qBtlQ+n4N85fGDsEtHbRDhA2uJhpONZpIh2Hok8UpjzZps86opbLvDXf07RgyZx1DiF/sYOdMK9LLEbGLlDcxtIG8=
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: agronholm/anyio

install: pip install -e .[test,curio,trio]

script: pytest
